databases:
  - name: text-editor-db
    plan: free
    postgresMajorVersion: 14

services:
  # Java Backend Web Servisi (Docker ile)
  - type: web
    name: ws-backend
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login
    envVars:
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: text-editor-db
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: text-editor-db
          property: port
      - key: SPRING_DATASOURCE_DB
        fromDatabase:
          name: text-editor-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: text-editor-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: text-editor-db
          property: password
      - key: PORT
        value: "10000"
      - key: Y_WEBSOCKET_BROWSER_URL
        value: "wss://y-websocket-svc.onrender.com"
      - key: Y_WEBSOCKET_URL
        value: "wss://y-websocket-svc.onrender.com"

  # Y-Websocket Servisi (Docker ile)
  - type: web
    name: y-websocket-svc
    plan: free
    env: docker
    dockerfilePath: ./y-websocket/Dockerfile
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "1234" 