databases:
  - name: text-editor-db
    plan: free
    postgresMajorVersion: 14

services:
  # Java Backend Web Servisi (Docker ile)
  - type: web
    name: ws-backend
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: text-editor-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: text-editor-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: text-editor-db
          property: password
      - key: Y_WEBSOCKET_BROWSER_URL
        value: "wss://y-websocket-svc.onrender.com"
      - key: Y_WEBSOCKET_URL
        value: "wss://y-websocket-svc.onrender.com"

  # Y-Websocket Servisi
  - type: web
    name: y-websocket-svc
    plan: free
    env: node
    # rootDir kaldırıldı, komutlar proje kökünden çalışacak
    buildCommand: "git submodule update --init --recursive && cd y-websocket && npm install"
    startCommand: "cd y-websocket && node src/y-websocket.js"
    healthCheckPath: "/" 