services:
  # PostgreSQL Veritabanı (hatalar düzeltildi)
  - type: pserv
    name: text-editor-db
    plan: free

  # Java Backend Web Servisi (artık Docker kullanıyor)
  - type: web
    name: ws-backend
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile # Az önce oluşturduğumuz Dockerfile'ın yolu
    healthCheckPath: /login
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: text-editor-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: text-editor-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: text-editor-db
          property: password
      - key: Y_WEBSOCKET_BROWSER_URL
        value: "wss://y-websocket-svc.onrender.com" # 'url' hatası düzeltildi
      - key: Y_WEBSOCKET_URL # Servisler arası iletişim için
        value: "wss://y-websocket-svc.onrender.com"

  # Y-Websocket Servisi (adı backend'e uyumlu hale getirildi)
  - type: web
    name: y-websocket-svc
    plan: free
    env: node
    rootDir: ./y-websocket
    buildCommand: "npm install"
    startCommand: "node src/y-websocket.js" # 'npm start' bazen sorun çıkarabilir, doğrudan dosyayı çalıştırıyoruz
    healthCheckPath: "/" 